export const AESTHETIC_QUERIES = [
  "clínica de harmonização facial",
  "clínica de harmonização orofacial",
  "harmonização facial",
  "harmonização orofacial",
  "clínica de estética avançada",
  "estética avançada",
  "clínica de estética facial",
  "clínica de estética",
  "clínica de injetáveis",
  "injetáveis estéticos",
  "biomédica esteta",
  "biomédico esteta",
  "biomedicina estética",
  "clínica de biomedicina estética",
  "dentista harmonização facial",
  "dentista harmonização orofacial",
  "odontologia estética",
  "clínica odontológica estética",
  "clínica odontológica harmonização facial",
  "especialista em harmonização orofacial",
  "dermatologista estética",
  "dermatologia estética",
  "clínica dermatológica estética",
  "medicina estética",
  "médico estética",
  "clínica de medicina estética",
  "cirurgia plástica estética",
  "cirurgião plástico",
  "rejuvenescimento facial",
  "rejuvenescimento estético",
  "estética facial",
  "preenchimento facial",
  "preenchimento labial",
  "botox",
  "toxina botulínica",
  "aplicação de botox",
  "bioestimulador de colágeno",
  "aplicação de bioestimulador",
  "fios de PDO",
  "skinbooster",
  "tratamento facial injetável",
  "harmonização de glúteo",
  "harmonização corporal",
  "estética corporal avançada",
  "clínica de rejuvenescimento",
] as const satisfies readonly string[];
